### ISSUE TITLE
OTU table as input

### ISSUE THREAD

**Issue by slambrechts** [SebH87/CoMA3#1]
Hi,

Can we use an OTU-table as input for CoMA? We have OTU tables with taxonomy added (in the last column), and i was wondering if we could use CoMA to generate figures/graphics?

Best,
Sam

**Comment by SebH87** [comment]
Hi Sam,

Absolutely! You can use your OTU-table and jump into the CoMA workflow at any step you want. Just make sure that the file is formatted correctly and named "abundance.txt". This file must be saved in a project directory (avoid all special characters apart from "_") within a subdirectory called "Results". The file should be formatted like this:

# Constructed from biom file
#OTU ID    sample1_name    sample2_name    ...
OTU/ASV1    sample1_count    sample2_count    ...
OTU/ASV2    sample1_count    sample2_count    ...
OTU/ASV3    sample1_count    sample2_count    ...
.
.
.

Tab must be the text delimiter.

For some steps (e.g., subsampling or singleton removal) you need a biom file (just convert the OTU-table with the biom-converter tool) and for some other steps (alpha diversity with FaithPD metric, beta diversity with UNIFRAC distance) you need a phylogenetic tree file in Newick format.

If you need any further help, do not hesitate to contact me again!

Cheers,

Sebastian

**Comment by slambrechts** [comment]
Hi Sebastian, 

Great, thanks!
